### ISSUE TITLE
Error:(49, 0) Could not find property 'release' on SigningConfig container.

### ISSUE THREAD

**Issue by kurasa** [kiideveloper/pokiimap#1]
Great Source Code.. but i'm trying ti import the SC i found error like this..
Error:(49, 0) Could not find property 'release' on SigningConfig container.

i'm using 0.3 version  , What should I do?

Thanks for Advice

**Comment by kiideveloper** [comment]
error was from build.gradle because I didnt check in my private key, etc. It should be fixed now.
