### ISSUE TITLE
Tap To Catch not work

### ISSUE THREAD

**Issue by kurasa** [kiideveloper/pokiimap#2]
hi.. thanks for the update.. i'm trying the source code i found error like this
1. cannot resolve symbol global_tracker at PokiiMapApplication.java
2. Tap To Catch not work.. 

please help me for resolve this error

regards

**Comment by kiideveloper** [comment]
please see source codes, you will know why

**Comment by kurasa** [comment]
what you mean sir.. :) I am a beginner and just learning about this. whether it's source code is not complete? because i'm trying alpha 0,6 still same.. tap to cath n tap to lot not work..

Thanks for advance

**Comment by kurasa** [comment]
please sir help me for tap to catch n tap to loot :) , because still error with alpha 0,7
