### ISSUE TITLE
Every Pokemon fleed

### ISSUE THREAD

**Issue by petemat** [kiideveloper/pokiimap#26]
Is there a trick to higher the catch rate? Its like all pokemon are fleeing...I tried all kinds of balls.

**Comment by ErwanLeroux** [comment]
Read the readme : [readme](https://github.com/kiideveloper/pokiimap#warning-if-you-try-to-catch-the-pokemon-and-they-all-fleed-that-means-you-teleport-too-much-and-is-temporarily-blocked-from-catching-anything-close-the-game-and-wait-15-mins-before-trying-it-again)

**Comment by petemat** [comment]
Thanks mate
