### ISSUE TITLE
[Suggestion] PokeSnipe

### ISSUE THREAD

**Issue by BadSly** [kiideveloper/pokiimap#35]
can you add a feature where we can directly put a lat/lon so we can directly go to that pokemon and catch it. :)

**Comment by ponnex** [comment]
This one is easy to integrate since it uses Google Map API hope kiisev will add this on next build. Although jumping from one place to another will result to "softban". You wont be able to catch, loot, battle on gym for the next 24hrs.

**Comment by kiideveloper** [comment]
this is doable but may take times
