### ISSUE TITLE
[Suggestion] Allow custom assets

### ISSUE THREAD

**Issue by iamvicbailon** [kiideveloper/pokiimap#45]
Is there a option to load our images from a server or url like "http://serebii.net/pokemongo/pokemon/{id}.png"? and the id is on 001 - 151.
So, the user only should put the url of the image in a input (Because some users doesn't like the assets that you use).

**Comment by Zerthox** [comment]
Copyright issues. All I have to say.

**Comment by theteebox** [comment]
from the 1st phase of developing we must take this for consideration. Copyright issues is the main reason why developer have the problems at the first place. we can appreciate them by not asking/requesting this kind of joke suggestion. Just my2cents

**Comment by iamvicbailon** [comment]
Yes I know the copyright, but if you use or put your own link, the developer isn't responsable of the use, and if put a warning of this, can be better.

**Comment by hardknoxni69a** [comment]
Can just be greaful that he shared the hard work he did for his wife not ungrateful cheaters complaining about a picture that he uses to be safe unlike all the other devs that could care less people that complain about stuff like that are why projects end

**Comment by kiideveloper** [comment]
i may be able to make it load an external icon pack, something for the future
