### ISSUE TITLE
Update function in 1.2.2

### ISSUE THREAD

**Issue by thebigsmileXD** [kiideveloper/pokiimap#48]
Version 1.2.2 tells me its the latest version. 1.2.3 just released.

**Comment by BadSly** [comment]
yeah, 1.2.3 is released, so download it now.

**Comment by thebigsmileXD** [comment]
@BadSly Before you answer, read carefully.
I said that the update function tells me there is no update.

BTW: After a restart teh update function still told me there's no update, but the popup message did.

**Comment by kiideveloper** [comment]
fixed
