### ISSUE TITLE
version 1.3.2 Empty Loot after using PokeSniper

### ISSUE THREAD

**Issue by cheenobautista** [kiideveloper/pokiimap#56]
I have updated my pokiimap app, and I used the sniper. I was unable to catch the pokemon identified and scanned at the specified location. I also used to scan in my current location and I can't seem to catch any pokemon and it always say "Empty Loot". But using my other account, not using sniping mode, the pokiimap functions as before.

Another thing I found, the name of the pokestop is not displayed but instead, "pokestop" as the default displayed name. A message is also displayed that says, "Null objects cannot be copied from Realm".

**Comment by kiideveloper** [comment]
check your account setting, add them back if they are gone.

**Comment by cheenobautista** [comment]
Thank you so much for your help. :) I have updated to the latest version as of this date. No issues encountered so far. Keep up the good work!
