### ISSUE TITLE
Eggs do not hatch anymore

### ISSUE THREAD

**Issue by Bittergal** [kiideveloper/pokiimap#58]
On the previous versions we could accumulate km to hatch eggs, but not anymore?

**Comment by Bittergal** [comment]
:(

**Comment by AllTheWay** [comment]
I believe this might be related to safe mode for the main account. Do you have Safe Mode turned on for main account? If you do I believe this might be the culprit.

**Comment by notmyusualname** [comment]
I had a quick look and it seems to be putting distance on the scan account but not the primary/loot account.

**Comment by kiideveloper** [comment]
on scan accounts are used to scan, primary is no longer used for scanning

**Comment by Bittergal** [comment]
I used my primary account to scan, but still not getting km?
