### ISSUE TITLE
[Question] Compability to .37/.39

### ISSUE THREAD

**Issue by Inuyasha22** [kiideveloper/pokiimap#98]
You say "don't use your main account" and so on...

But how's the chances of Niantic's system finding out you're using the tool instead of Pokemon Go? Has this been updated to match the update's changes, as in the past?

**Comment by hardknoxni69a** [comment]
.39/37 api has not been cracked DO NOT use your main account or you or truly sticking your head out like whack a mole chances of not getting banned is like %.0000000000000001

**Comment by Inuyasha22** [comment]
More like whack a diglet :3 Oh well, thanks.
